import { LoadingButton } from "@mui/lab";
import {
  Alert,
  Card,
  CardContent,
  Grid,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";

import { createTranscript, generateSoap } from "../../shared/services/scribeService";
import { generateSummary } from "../../shared/services/summarizerService";

export const ScribePage = () => {
  const [encounterId, setEncounterId] = useState("");
  const [transcript, setTranscript] = useState("");

  const createTranscriptMutation = useMutation({
    mutationFn: () => createTranscript({ encounter_id: encounterId, transcript }),
  });

  const soapMutation = useMutation({
    mutationFn: () => generateSoap(encounterId, transcript),
  });

  const summaryMutation = useMutation({
    mutationFn: (soapNote: string) =>
      generateSummary({
        patient_id: soapMutation.data?.encounter_id ?? "",
        encounter_ids: [soapMutation.data?.encounter_id ?? ""],
        highlights: [soapNote],
      }),
  });

  const handleGenerate = async () => {
    await createTranscriptMutation.mutateAsync();
    const note = await soapMutation.mutateAsync();
    await summaryMutation.mutateAsync(note.plan ?? "Plan pending.");
  };

  return (
    <Grid container spacing={3}>
      <Grid item xs={12}>
        <Typography variant="h4">Clinical Documentation</Typography>
        <Typography variant="body1" color="text.secondary">
          Capture transcripts and generate SOAP notes that flow into patient timelines and summaries.
        </Typography>
      </Grid>
      <Grid item xs={12} md={6}>
        <Card>
          <CardContent>
            <Stack spacing={2}>
              <TextField
                label="Encounter ID"
                value={encounterId}
                onChange={(event) => setEncounterId(event.target.value)}
                helperText="Use encounter IDs generated by the manage-agent."
                required
              />
              <TextField
                label="Transcript"
                value={transcript}
                onChange={(event) => setTranscript(event.target.value)}
                multiline
                minRows={8}
                placeholder="Doctor: Tell me about your symptoms..."
              />
              <LoadingButton
                variant="contained"
                onClick={handleGenerate}
                loading={
                  createTranscriptMutation.isPending ||
                  soapMutation.isPending ||
                  summaryMutation.isPending
                }
                disabled={!encounterId || !transcript}
              >
                Generate SOAP & Summary
              </LoadingButton>
            </Stack>
          </CardContent>
        </Card>
      </Grid>
      <Grid item xs={12} md={6}>
        {soapMutation.data && (
          <Card sx={{ mb: 2 }}>
            <CardContent>
              <Typography variant="h6">SOAP Note</Typography>
              <Typography variant="subtitle2" sx={{ mt: 1 }}>
                Subjective
              </Typography>
              <Typography variant="body2">{soapMutation.data.subjective}</Typography>
              <Typography variant="subtitle2" sx={{ mt: 1 }}>
                Assessment
              </Typography>
              <Typography variant="body2">{soapMutation.data.assessment}</Typography>
              <Typography variant="subtitle2" sx={{ mt: 1 }}>
                Plan
              </Typography>
              <Typography variant="body2">{soapMutation.data.plan}</Typography>
            </CardContent>
          </Card>
        )}
        {summaryMutation.data && (
          <Alert severity="success">
            Summary generated and stored for patient {summaryMutation.data.patient_id}.
          </Alert>
        )}
      </Grid>
    </Grid>
  );
};

